name: Deploy LFS files to GitHub Pages

on:
  push:
    branches:
      - main  # 你可以根据实际情况修改分支名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true  # 确保下载LFS文件

    - name: Install Git LFS
      run: |
        git lfs install
        git lfs pull  # 拉取LFS文件

    - name: Build your static site (if necessary)
      run: |
        echo "Build steps here"  # 如果你的项目需要构建静态站点，请在这里添加构建步骤

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data  # 设置为包含LFS文件的目录
